### PR TITLE
Fixes #95 --> address issues found in rst files

### LINKED ISSUE #95: Issue #95 --> address found issues in rst files
While converting into markdown, found some areas where there was no alt text, missing questions, private links and no formatting on images.

### PR DESCRIPTION
**Pull request by lindseyc**
addressed previous stated found issues in files @raskutti

### CODE REVIEW

**Review by raskutti — APPROVED** [review]
This looks great to me. Have you verified that these changes all look good in runestone? @lindseyc

**Comment by lindseyc** [comment]
@raskutti for some reason the summaries are not showing up in runestone on the table of contents, but they are there when I go through the pages. Also I tried a few different ways but even in Latex format the exponents in one section would not become superscript

**Comment by lindseyc** [comment]
figured out why the summaries aren't showing up

**Comment by lindseyc** [comment]
and found the right exponent notation - will fix

**Comment by lindseyc** [comment]
@raskutti fixed summaries and exponents

**Pull request merged**
